export const AcometidaModel = [
  {
    databaseName: "acometidas",
    registerLabel: "Registrar Acometida",
    updateLabel: "Actualizar Acometida",
  },
  [
    { name: "codigo", label: "Código", type: "string" },
    {
      name: "fases",
      label: "Fases",
      type: "list",
      values: [{ label: "XXX", value: "xxx" }],
    },
    {
      name: "transformador",
      label: "Transformador",
      type: "list",
      values: [{ label: "XXX", value: "xxx" }],
    },
    {
      name: "circuito",
      label: "Circuito",
      type: "list",
      values: [
        { label: "CP12", value: "CP12" },
        { label: "CP13", value: "CP13" },
        { label: "CP14", value: "CP14" },
        { label: "CP17", value: "CP17" },
        { label: "CP21", value: "CP21" },
        { label: "CP22", value: "CP22" },
        { label: "CP23", value: "CP23" },
        { label: "CP24", value: "CP24" },
        { label: "CP25", value: "CP25" },
        { label: "CP31", value: "CP31" },
        { label: "CP32", value: "CP32" },
        { label: "CP33", value: "CP33" },
        { label: "CP45", value: "CP45" },
        { label: "CP46", value: "CP46" },
      ],
    },
    { name: "nodo", label: "Nodo-Poste", type: "string" },
    {
      name: "conductor",
      label: "Conductor",
      type: "list",
      values: [{ label: "XXX", value: "xxx" }],
    },
    {
      name: "neutro",
      label: "Neutro",
      type: "list",
      values: [{ label: "XXX", value: "xxx" }],
    },
    {
      name: "poblacion",
      label: "Población",
      type: "list",
      values: [
        { label: "Urbano", value: "Urbano" },
        { label: "Rural", value: "Rural" },
        { label: "Centro", value: "Poblado" },
      ],
    },
    {
      name: "fecha_levantamiento",
      label: "Fecha de Levantamiento",
      type: "date",
    },
    { name: "latitud_niu", label: "Latitud-Niu", type: "real" },
    { name: "longitud_niu", label: "Longitu-Niu", type: "real" },
    { name: "latitud_poste", label: "Latitud-Poste", type: "real" },
    { name: "longitud_poste", label: "longitud-Poste", type: "real" },
  ],
];
