export const AcometidaModel = [
  {
    databaseName: "acometidas",
    registerLabel: "Registrar Acometida",
    updateLabel: "Actualizar Acometida",
  },
  [
    { name: "codigo", label: "Código", type: "string", format: "numeric" },
    {
      name: "fases",
      label: "Fases",
      type: "string",
      format: "default",
      values: [{ label: "NO data", value: "NO data" }],
    },
    {
      name: "transformador",
      label: "Transformador",
      type: "string",
      format: "default",
      values: [{ label: "NO data", value: "NO data" }],
    },
    {
      name: "circuito",
      label: "Circuito",
      type: "string",
      format: "default",
      values: [
        { label: "CP12", value: "CP12" },
        { label: "CP13", value: "CP13" },
        { label: "CP14", value: "CP14" },
        { label: "CP17", value: "CP17" },
        { label: "CP21", value: "CP21" },
        { label: "CP22", value: "CP22" },
        { label: "CP23", value: "CP23" },
        { label: "CP24", value: "CP24" },
        { label: "CP25", value: "CP25" },
        { label: "CP31", value: "CP31" },
        { label: "CP32", value: "CP32" },
        { label: "CP33", value: "CP33" },
        { label: "CP45", value: "CP45" },
        { label: "CP46", value: "CP46" },
      ],
    },
    { name: "nodo", label: "Nodo-Poste", type: "string", format: "default" },
    {
      name: "conductor",
      label: "Conductor",
      type: "string",
      format: "default",
      values: [{ label: "NO data", value: "NO data" }],
    },
    {
      name: "neutro",
      label: "Neutro",
      type: "string",
      format: "default",
      values: [{ label: "NO data", value: "NO data" }],
    },
    {
      name: "poblacion",
      label: "Población",
      type: "string",
      format: "numeric",
      values: [
        { label: "Urbano", value: "Urbano" },
        { label: "Rural", value: "Rural" },
        { label: "Centro", value: "Poblado" },
      ],
    },
    // {
    //   name: "fecha_levantamiento",
    //   label: "Fecha de Levantamiento",
    //   type: "date",
    // },
    {
      name: "latitud_niu",
      label: "Latitud-Niu",
      type: "real",
      format: "decimal-pad",
    },
    {
      name: "longitud_niu",
      label: "Longitu-Niu",
      type: "real",
      format: "decimal-pad",
    },
    {
      name: "latitud_poste",
      label: "Latitud-Poste",
      type: "real",
      format: "decimal-pad",
    },
    {
      name: "longitud_poste",
      label: "longitud-Poste",
      type: "real",
      format: "decimal-pad",
    },
  ],
];
